services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # apiportal:
  #   build:
  #     context: ../apps/apiportal
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ../apps/apiportal/app.env
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:

networks:
  default:
    name: kakeiboku_network